// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2DGEhE4S2l6V4aGfXWnqzfvGVQ8wOAzo',
    appId: '1:303110780746:web:9a128a60113a37916e33b3',
    messagingSenderId: '303110780746',
    projectId: 'chat-app-c4c60',
    authDomain: 'chat-app-c4c60.firebaseapp.com',
    storageBucket: 'chat-app-c4c60.appspot.com',
    measurementId: 'G-NXFMWPB9G4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXVbVtype0aFX8U8Q4VqXzB2pIB3c7XDg',
    appId: '1:303110780746:android:6e8399c96ae038276e33b3',
    messagingSenderId: '303110780746',
    projectId: 'chat-app-c4c60',
    storageBucket: 'chat-app-c4c60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuskrNb19r3eYf4H4mUzSQjOt1_3x2E-M',
    appId: '1:303110780746:ios:1558e6128d1f70346e33b3',
    messagingSenderId: '303110780746',
    projectId: 'chat-app-c4c60',
    storageBucket: 'chat-app-c4c60.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuskrNb19r3eYf4H4mUzSQjOt1_3x2E-M',
    appId: '1:303110780746:ios:9f9aa826c24a4db86e33b3',
    messagingSenderId: '303110780746',
    projectId: 'chat-app-c4c60',
    storageBucket: 'chat-app-c4c60.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
